export default [
  {
    clientNumber: "1",
    ownerName: "Nick Braddock",
    email: "nicholas.braddock@student.swic.edu",
    cell: "1234567890",
    home: "1234567890",
    street: "123 First Street",
    city: "O'Fallon",
    state: "IL",
    zip: "62269",
    petName: "Rudy",
    dob: "2019-02-09",
    species: "Dog",
    breed: "Poodle",
    color: "Red",
    sex: "Male",
    sexuallyIntact: "No, Neutered",
    shotsCurrent: "Yes",
  },
];
